<?php namespace App;

/**
 * Eloquent class to describe the cursos table
 *
 * automatically generated by ModelGenerator.php
 */
class Cursos extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'cursos';

    protected $fillable = array('file');

}

