<?php namespace App;

/**
 * Eloquent class to describe the preguntas table
 *
 * automatically generated by ModelGenerator.php
 */
class Preguntas extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'preguntas';

    public $timestamps = false;

    protected $fillable = array('pregunta');

    public function respuestas()
    {
        return $this->hasMany('App\Respuestas', 'preguntas_id', 'id');
    }

}

