<?php namespace App;

/**
 * Eloquent class to describe the respuestas table
 *
 * automatically generated by ModelGenerator.php
 */
class Respuestas extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'respuestas';

    public $timestamps = false;

    protected $fillable = array('respuesta', 'boolean');

    public function preguntas()
    {
        return $this->belongsTo('App\Preguntas', 'preguntas_id', 'id');
    }

}

